screen_width  = 1280 
screen_height = 720

### CONSTANTS
BOARD_CELL_SIZE = 96
BOARD_OFFSET_TOP = 172
BOARD_OFFSET_LEFT = 112

SEEDS_BANK_OFFSET_TOP = 10
SEEDS_BANK_OFFSET_LEFT = 10
SEEDS_BANK_WIDTH = 154
SEEDS_BANK_HEIGHT = 36

SEEDS_CARDS_LEFT_OFFSET = 80
SEED_CARD_WIDTH = 62
SEED_CARD_HEIGHT = 70

PLANT_WIDTH = 90
PLANT_HEIGHT = 90

ZOMBIE_WIDTH = 110
ZOMBIE_HEIGHT = 110
ZOMBIE_BOTTOM_OFFSET = 10
ZOMBIE_TOP_OVERLAP = 32
ZOMBIE_HITBOX_OFFSET = 9
### CONSTANTS

DRAW_HEALTH_BARS = True
SHOW_DEBUG = False
SHOW_LEVEL_LOAD_DATA = False
SHOW_ZOMBIE_DATA = False
SHOW_FPS = False

